###
GET  http://64.225.20.73:4000/api/employees

###
POST  http://64.225.20.73:4000/api/employees
Content-Type: application/json

{
    "name" : "Anahi",
    "position": "Junior developer",
    "office": "Cowork",
    "salary": "50000"
}
###
GET http://64.225.20.73:4000/api/employees/5fea87533f1e4088d14591b2

###
DELETE  http://64.225.20.73:4000/api/employees/5fea87533f1e4088d14591b2

###
PUT http://64.225.20.73:4000/api/employees/5fea87533f1e4088d14591b2
Content-Type: application/json

{
    "name": "Sary Camas",
    "position": "Ling"
}